
spring:
#  autoconfigure:
#    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  datasource:
    url: jdbc:h2:tcp://192.168.0.119:9092//data/dongwook/h2/viver
    driver-class-name: org.h2.Driver
    username: sa
    password: 