
spring:
#  autoconfigure:
#    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
#  datasource:
#    url: jdbc:h2:tcp://localhost/~/viver
#    driver-class-name: org.h2.Driver
#    username: sa
#    password: 
   datasource:
     url: jdbc:postgresql://viver.ci0w0otlg937.us-east-2.rds.amazonaws.com:5432/postgres
     username: inis
     password: inis1234
     driver-class-name: org.postgresql.Driver


kakao:
  client:
    id: 7e6f9285b35e1c5af2ae9e3da753d37e
    secret: 0YrMY3nahxP6yvFxmRNaKoKtL9qSt7Ug

token:
  secret: ENC(9c9uJh1XDJMe72tcz8o94Z1pqQxRrUdKaxFAlScPFuIGZtp57tFR3Q==) # 
  access-token-expiration-time: 1  #
  refresh-token-expiration-time: 1 # 
  
#api key
api : 
  kopis : bbf08c05fac24dfbb7d8d741014869fe
  tmdb : 85b0b0fb6cf5bd7e1276742dc568a958