
spring:
#  autoconfigure:
#    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
#  datasource:
#    url: jdbc:h2:tcp://localhost/~/viver
#    driver-class-name: org.h2.Driver
#    username: sa
#    password: 
   datasource:
     url: jdbc:postgresql://viver.ci0w0otlg937.us-east-2.rds.amazonaws.com:5432/postgres?currentSchema=viver
     username: inis
     password: inis1234
     driver-class-name: org.postgresql.Driver
   jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true


kakao:
  client:
    id: 2f158d432028817e83bd31c036395602
    secret: JJy7MGMURuJkmlbAW4u4CgusXALbTKhN

naver:
    client:
      id: pHlFjtbzs_yxJID83EcM
      secret: QALT91rnUW
      
token:
  secret: ENC(9c9uJh1XDJMe72tcz8o94Z1pqQxRrUdKaxFAlScPFuIGZtp57tFR3Q==) # 
  access-token-expiration-time: 3600   #1시간
  refresh-token-expiration-time: 2592000  # 30일
  
#api key
api : 
  kopis : bbf08c05fac24dfbb7d8d741014869fe
  tmdb : 85b0b0fb6cf5bd7e1276742dc568a958
  language: ko-KR
  
#api base url
baseUrl:
  kopis : http://kopis.or.kr/openApi/restful
  tmdb: https://api.themoviedb.org/3